<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE HealthData [
<!-- HealthKit Export Version: 3 -->
<!ELEMENT HealthData (ExportDate,Me,(Record|Correlation|Workout|ActivitySummary)*)>
<!ATTLIST HealthData
  locale CDATA #REQUIRED
>
<!ELEMENT ExportDate EMPTY>
<!ATTLIST ExportDate
  value CDATA #REQUIRED
>
<!ELEMENT Me EMPTY>
<!ATTLIST Me
  HKCharacteristicTypeIdentifierDateOfBirth         CDATA #REQUIRED
  HKCharacteristicTypeIdentifierBiologicalSex       CDATA #REQUIRED
  HKCharacteristicTypeIdentifierBloodType           CDATA #REQUIRED
  HKCharacteristicTypeIdentifierFitzpatrickSkinType CDATA #REQUIRED
>
<!ELEMENT Record (MetadataEntry*)>
<!ATTLIST Record
  type          CDATA #REQUIRED
  unit          CDATA #IMPLIED
  value         CDATA #IMPLIED
  sourceName    CDATA #REQUIRED
  sourceVersion CDATA #IMPLIED
  device        CDATA #IMPLIED
  creationDate  CDATA #IMPLIED
  startDate     CDATA #REQUIRED
  endDate       CDATA #REQUIRED
>
<!-- Note: Any Records that appear as children of a correlation also appear as top-level records in this document. -->
<!ELEMENT Correlation ((MetadataEntry|Record)*)>
<!ATTLIST Correlation
  type          CDATA #REQUIRED
  sourceName    CDATA #REQUIRED
  sourceVersion CDATA #IMPLIED
  device        CDATA #IMPLIED
  creationDate  CDATA #IMPLIED
  startDate     CDATA #REQUIRED
  endDate       CDATA #REQUIRED
>
<!ELEMENT Workout ((MetadataEntry|WorkoutEvent)*)>
<!ATTLIST Workout
  workoutActivityType   CDATA #REQUIRED
  duration              CDATA #IMPLIED
  durationUnit          CDATA #IMPLIED
  totalDistance         CDATA #IMPLIED
  totalDistanceUnit     CDATA #IMPLIED
  totalEnergyBurned     CDATA #IMPLIED
  totalEnergyBurnedUnit CDATA #IMPLIED
  sourceName            CDATA #REQUIRED
  sourceVersion         CDATA #IMPLIED
  device                CDATA #IMPLIED
  creationDate          CDATA #IMPLIED
  startDate             CDATA #REQUIRED
  endDate               CDATA #REQUIRED
>
<!ELEMENT WorkoutEvent EMPTY>
<!ATTLIST WorkoutEvent
  type CDATA #REQUIRED
  date CDATA #REQUIRED
>
<!ELEMENT ActivitySummary EMPTY>
<!ATTLIST ActivitySummary
  dateComponents           CDATA #IMPLIED
  activeEnergyBurned       CDATA #IMPLIED
  activeEnergyBurnedGoal   CDATA #IMPLIED
  activeEnergyBurnedUnit   CDATA #IMPLIED
  appleExerciseTime        CDATA #IMPLIED
  appleExerciseTimeGoal    CDATA #IMPLIED
  appleStandHours          CDATA #IMPLIED
  appleStandHoursGoal      CDATA #IMPLIED
>
<!ELEMENT MetadataEntry EMPTY>
<!ATTLIST MetadataEntry
  key   CDATA #REQUIRED
  value CDATA #REQUIRED
>
]>
<HealthData locale="en_US">
 <ExportDate value="2017-11-07 10:05:13 +0200"/>
 <Me HKCharacteristicTypeIdentifierDateOfBirth="" HKCharacteristicTypeIdentifierBiologicalSex="HKBiologicalSexNotSet" HKCharacteristicTypeIdentifierBloodType="HKBloodTypeNotSet" HKCharacteristicTypeIdentifierFitzpatrickSkinType="HKFitzpatrickSkinTypeNotSet"/>
 <Record type="HKQuantityTypeIdentifierBloodGlucose" sourceName="Health" sourceVersion="10.2.1" unit="mg/dL" creationDate="2017-03-30 09:29:59 +0200" startDate="2017-03-30 09:29:00 +0200" endDate="2017-03-30 09:29:00 +0200" value="81">
  <MetadataEntry key="HKWasUserEntered" value="1"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierBloodGlucose" sourceName="Health" sourceVersion="10.3.1" unit="mg/dL" creationDate="2017-05-23 09:49:16 +0200" startDate="2017-05-23 09:49:00 +0200" endDate="2017-05-23 09:49:00 +0200" value="90">
  <MetadataEntry key="HKWasUserEntered" value="1"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierBloodGlucose" sourceName="Health" sourceVersion="10.3.1" unit="mg/dL" creationDate="2017-05-23 11:07:46 +0200" startDate="2017-05-23 11:07:00 +0200" endDate="2017-05-23 11:07:00 +0200" value="80">
  <MetadataEntry key="HKWasUserEntered" value="1"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierBloodGlucose" sourceName="Health" sourceVersion="10.3.1" unit="mg/dL" creationDate="2017-05-23 12:42:27 +0200" startDate="2017-05-23 12:42:00 +0200" endDate="2017-05-23 12:42:00 +0200" value="115">
  <MetadataEntry key="HKWasUserEntered" value="1"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierBloodGlucose" sourceName="Health" sourceVersion="10.3.1" unit="mg/dL" creationDate="2017-05-24 13:43:46 +0200" startDate="2017-05-24 13:43:00 +0200" endDate="2017-05-24 13:43:00 +0200" value="666">
  <MetadataEntry key="HKWasUserEntered" value="1"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierBloodGlucose" sourceName="mySugr" sourceVersion="1661" unit="mg/dL" creationDate="2017-05-24 14:00:05 +0200" startDate="2017-05-24 13:56:15 +0200" endDate="2017-05-24 13:56:15 +0200" value="166">
  <MetadataEntry key="HKExternalUUID" value="4F4542BB-252C-4525-B744-3D8FD424242F"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierBloodGlucose" sourceName="One Drop" sourceVersion="3.8.0.0" unit="mg/dL" creationDate="2017-05-24 14:07:09 +0200" startDate="2017-05-24 13:56:15 +0200" endDate="2017-05-24 13:56:15 +0200" value="166">
  <MetadataEntry key="App Source" value="OneDrop"/>
  <MetadataEntry key="HKWasUserEntered" value="0"/>
  <MetadataEntry key="HKExternalUUID" value="cGUtCSb2TIwLQwlHMvxQbbRv9ZiiAh9j"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierBloodGlucose" sourceName="One Drop" sourceVersion="3.8.0.0" unit="mg/dL" creationDate="2017-05-24 14:07:09 +0200" startDate="2017-05-23 09:49:00 +0200" endDate="2017-05-23 09:49:00 +0200" value="90">
  <MetadataEntry key="App Source" value="OneDrop"/>
  <MetadataEntry key="HKWasUserEntered" value="0"/>
  <MetadataEntry key="HKExternalUUID" value="75k8dkEN1ogbmbDPc7BNse4ovF5dIewc"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierBloodGlucose" sourceName="One Drop" sourceVersion="3.8.0.0" unit="mg/dL" creationDate="2017-05-24 14:07:09 +0200" startDate="2017-05-24 13:37:44 +0200" endDate="2017-05-24 13:37:44 +0200" value="98">
  <MetadataEntry key="App Source" value="OneDrop"/>
  <MetadataEntry key="HKWasUserEntered" value="0"/>
  <MetadataEntry key="HKExternalUUID" value="lwltJM2erH14SwoCR8MMHP6SoSsvON4E"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierBloodGlucose" sourceName="One Drop" sourceVersion="3.8.0.0" unit="mg/dL" creationDate="2017-05-24 14:07:09 +0200" startDate="2017-05-23 11:07:00 +0200" endDate="2017-05-23 11:07:00 +0200" value="80">
  <MetadataEntry key="App Source" value="OneDrop"/>
  <MetadataEntry key="HKWasUserEntered" value="0"/>
  <MetadataEntry key="HKExternalUUID" value="qUrF43plTnosXfg6OzMC4vIt5QsZVFFm"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierBloodGlucose" sourceName="One Drop" sourceVersion="3.8.0.0" unit="mg/dL" creationDate="2017-05-24 14:07:09 +0200" startDate="2017-05-23 12:42:00 +0200" endDate="2017-05-23 12:42:00 +0200" value="115">
  <MetadataEntry key="App Source" value="OneDrop"/>
  <MetadataEntry key="HKWasUserEntered" value="0"/>
  <MetadataEntry key="HKExternalUUID" value="3NbkZA6VbvH9qQXWYVHZOEQI2fn1nfZ0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierBloodGlucose" sourceName="One Drop" sourceVersion="3.8.0.0" unit="mg/dL" creationDate="2017-05-24 14:07:09 +0200" startDate="2017-05-24 13:43:00 +0200" endDate="2017-05-24 13:43:00 +0200" value="666">
  <MetadataEntry key="App Source" value="OneDrop"/>
  <MetadataEntry key="HKWasUserEntered" value="0"/>
  <MetadataEntry key="HKExternalUUID" value="yv0zIuHmV075DrhjtROseVHVf0MdqXus"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierBloodGlucose" sourceName="One Drop" sourceVersion="3.8.0.0" unit="mg/dL" creationDate="2017-05-24 14:07:16 +0200" startDate="2017-05-24 14:07:11 +0200" endDate="2017-05-24 14:07:11 +0200" value="58">
  <MetadataEntry key="App Source" value="OneDrop"/>
  <MetadataEntry key="HKWasUserEntered" value="1"/>
  <MetadataEntry key="HKExternalUUID" value="PfaYfThcQaCQlXFkSAH3W4SFSbGtPW3t"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierBloodGlucose" sourceName="One Drop" sourceVersion="3.8.0.0" unit="mg/dL" creationDate="2017-05-24 16:07:48 +0200" startDate="2017-05-24 14:33:16 +0200" endDate="2017-05-24 14:33:16 +0200" value="70">
  <MetadataEntry key="App Source" value="OneDrop"/>
  <MetadataEntry key="HKWasUserEntered" value="0"/>
  <MetadataEntry key="HKExternalUUID" value="MquxWsXwnwYjNuuvW93xPmFNkVZ7h7zX"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierBloodGlucose" sourceName="Health" sourceVersion="10.3.1" unit="mg/dL" creationDate="2017-05-25 13:58:55 +0200" startDate="2017-05-25 13:58:00 +0200" endDate="2017-05-25 13:58:00 +0200" value="99">
  <MetadataEntry key="HKWasUserEntered" value="1"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierBloodGlucose" sourceName="mySugr" sourceVersion="1661" unit="mg/dL" creationDate="2017-05-25 14:01:27 +0200" startDate="2017-05-25 13:58:54 +0200" endDate="2017-05-25 13:58:54 +0200" value="111">
  <MetadataEntry key="HKExternalUUID" value="AD185FE9-F7C1-43B9-9DFF-CB5BCA40E1B2"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierBloodGlucose" sourceName="One Drop" sourceVersion="3.8.0.0" unit="mg/dL" creationDate="2017-05-25 14:02:29 +0200" startDate="2017-05-25 13:58:54 +0200" endDate="2017-05-25 13:58:54 +0200" value="111">
  <MetadataEntry key="App Source" value="OneDrop"/>
  <MetadataEntry key="HKWasUserEntered" value="0"/>
  <MetadataEntry key="HKExternalUUID" value="kJj8huH67dMXMUTuE5AyO7PPbsSugEvV"/>
 </Record>
 
 </Record>
 <Record type="HKCategoryTypeIdentifierSleepAnalysis" sourceName="Pillow" sourceVersion="096" creationDate="2017-06-20 06:27:52 +0200" startDate="2017-06-19 21:41:16 +0200" endDate="2017-06-20 06:27:51 +0200" value="HKCategoryValueSleepAnalysisAsleep">
  <MetadataEntry key="HKTimeZone" value="Asia/Jerusalem"/>
 </Record>
 <Record type="HKCategoryTypeIdentifierSleepAnalysis" sourceName="Pillow" sourceVersion="096" creationDate="2017-06-20 06:27:52 +0200" startDate="2017-06-19 21:41:16 +0200" endDate="2017-06-20 06:27:51 +0200" value="HKCategoryValueSleepAnalysisInBed">
  <MetadataEntry key="HKTimeZone" value="Asia/Jerusalem"/>
 </Record>
 <Record type="HKCategoryTypeIdentifierSleepAnalysis" sourceName="SleepTrack" sourceVersion="3" creationDate="2017-07-18 09:23:37 +0200" startDate="2017-06-19 21:39:22 +0200" endDate="2017-06-20 06:28:13 +0200" value="HKCategoryValueSleepAnalysisAsleep"/>
 <Record type="HKCategoryTypeIdentifierSleepAnalysis" sourceName="Health" sourceVersion="10.3.1" creationDate="2017-06-20 14:22:51 +0200" startDate="2017-06-20 11:00:00 +0200" endDate="2017-06-20 13:00:00 +0200" value="HKCategoryValueSleepAnalysisAsleep">
  <MetadataEntry key="HKWasUserEntered" value="1"/>
 </Record>
  <Record type="HKQuantityTypeIdentifierDietaryProtein" sourceName="Nutrino" sourceVersion="2.15.0.6" unit="g" creationDate="2017-11-02 11:21:48 +0200" startDate="2017-11-03 00:00:00 +0200" endDate="2017-11-03 00:00:00 +0200" value="18">
   <MetadataEntry key="Meal" value="meal"/>
   <MetadataEntry key="HKFoodType" value="Super Berry Smoothie"/>
  </Record>
  <Record type="HKQuantityTypeIdentifierDietaryFatTotal" sourceName="Nutrino" sourceVersion="2.15.0.6" unit="g" creationDate="2017-11-02 11:21:48 +0200" startDate="2017-11-03 00:00:00 +0200" endDate="2017-11-03 00:00:00 +0200" value="15">
   <MetadataEntry key="Meal" value="meal"/>
   <MetadataEntry key="HKFoodType" value="Super Berry Smoothie"/>
  </Record>
  <Record type="HKQuantityTypeIdentifierDietaryEnergyConsumed" sourceName="Nutrino" sourceVersion="2.15.0.6" unit="kcal" creationDate="2017-11-02 11:21:48 +0200" startDate="2017-11-03 00:00:00 +0200" endDate="2017-11-03 00:00:00 +0200" value="540">
   <MetadataEntry key="Meal" value="meal"/>
   <MetadataEntry key="HKFoodType" value="Super Berry Smoothie"/>
  </Record>
 </Correlation>
 <Correlation type="HKCorrelationTypeIdentifierFood" sourceName="Nutrino" sourceVersion="2.15.0.6" creationDate="2017-11-02 11:22:21 +0200" startDate="2017-11-03 00:00:00 +0200" endDate="2017-11-03 00:00:00 +0200">
  <MetadataEntry key="HKExternalUUID" value="acu0jkcg#AV98CcuAPgcAXyyTJ4Xn"/>
  <MetadataEntry key="HKFoodType" value="Power Pooch Smoothies"/>
  <Record type="HKQuantityTypeIdentifierDietaryFatTotal" sourceName="Nutrino" sourceVersion="2.15.0.6" unit="g" creationDate="2017-11-02 11:22:21 +0200" startDate="2017-11-03 00:00:00 +0200" endDate="2017-11-03 00:00:00 +0200" value="1.5">
   <MetadataEntry key="Meal" value="meal"/>
   <MetadataEntry key="HKFoodType" value="Power Pooch Smoothies"/>
  </Record>
  <Record type="HKQuantityTypeIdentifierDietaryCarbohydrates" sourceName="Nutrino" sourceVersion="2.15.0.6" unit="g" creationDate="2017-11-02 11:22:21 +0200" startDate="2017-11-03 00:00:00 +0200" endDate="2017-11-03 00:00:00 +0200" value="26">
   <MetadataEntry key="Meal" value="meal"/>
   <MetadataEntry key="HKFoodType" value="Power Pooch Smoothies"/>
  </Record>
  <Record type="HKQuantityTypeIdentifierDietaryProtein" sourceName="Nutrino" sourceVersion="2.15.0.6" unit="g" creationDate="2017-11-02 11:22:21 +0200" startDate="2017-11-03 00:00:00 +0200" endDate="2017-11-03 00:00:00 +0200" value="3">
   <MetadataEntry key="Meal" value="meal"/>
   <MetadataEntry key="HKFoodType" value="Power Pooch Smoothies"/>
  </Record>
  <Record type="HKQuantityTypeIdentifierDietaryEnergyConsumed" sourceName="Nutrino" sourceVersion="2.15.0.6" unit="kcal" creationDate="2017-11-02 11:22:21 +0200" startDate="2017-11-03 00:00:00 +0200" endDate="2017-11-03 00:00:00 +0200" value="130">
   <MetadataEntry key="Meal" value="meal"/>
   <MetadataEntry key="HKFoodType" value="Power Pooch Smoothies"/>
  </Record>
 </Correlation>
 <Correlation type="HKCorrelationTypeIdentifierFood" sourceName="Nutrino" sourceVersion="2.15.0.6" creationDate="2017-11-02 11:22:21 +0200" startDate="2017-11-03 00:00:00 +0200" endDate="2017-11-03 00:00:00 +0200">
  <MetadataEntry key="HKExternalUUID" value="acu0jkcg#AV98CcuAPgcAXyyTJ4Xo"/>
  <MetadataEntry key="HKFoodType" value="Zucchini-Basil Soup"/>
  <Record type="HKQuantityTypeIdentifierDietaryProtein" sourceName="Nutrino" sourceVersion="2.15.0.6" unit="g" creationDate="2017-11-02 11:22:21 +0200" startDate="2017-11-03 00:00:00 +0200" endDate="2017-11-03 00:00:00 +0200" value="2">
   <MetadataEntry key="Meal" value="meal"/>
   <MetadataEntry key="HKFoodType" value="Zucchini-Basil Soup"/>
  </Record>
  <Record type="HKQuantityTypeIdentifierDietaryEnergyConsumed" sourceName="Nutrino" sourceVersion="2.15.0.6" unit="kcal" creationDate="2017-11-02 11:22:21 +0200" startDate="2017-11-03 00:00:00 +0200" endDate="2017-11-03 00:00:00 +0200" value="140">
   <MetadataEntry key="Meal" value="meal"/>
   <MetadataEntry key="HKFoodType" value="Zucchini-Basil Soup"/>
  </Record>
  <Record type="HKQuantityTypeIdentifierDietaryCarbohydrates" sourceName="Nutrino" sourceVersion="2.15.0.6" unit="g" creationDate="2017-11-02 11:22:21 +0200" startDate="2017-11-03 00:00:00 +0200" endDate="2017-11-03 00:00:00 +0200" value="8">
   <MetadataEntry key="Meal" value="meal"/>
   <MetadataEntry key="HKFoodType" value="Zucchini-Basil Soup"/>
  </Record>
  <Record type="HKQuantityTypeIdentifierDietaryFatTotal" sourceName="Nutrino" sourceVersion="2.15.0.6" unit="g" creationDate="2017-11-02 11:22:21 +0200" startDate="2017-11-03 00:00:00 +0200" endDate="2017-11-03 00:00:00 +0200" value="11">
   <MetadataEntry key="Meal" value="meal"/>
   <MetadataEntry key="HKFoodType" value="Zucchini-Basil Soup"/>
  </Record>
 </Correlation>
 <Correlation type="HKCorrelationTypeIdentifierFood" sourceName="Nutrino" sourceVersion="2.15.0.6" creationDate="2017-11-02 11:22:21 +0200" startDate="2017-11-03 00:00:00 +0200" endDate="2017-11-03 00:00:00 +0200">
  <MetadataEntry key="HKExternalUUID" value="acu0jkcg#AV98CcuAPgcAXyyTJ4Xp"/>
  <MetadataEntry key="HKFoodType" value="Air-Popped Popcorn"/>
  <Record type="HKQuantityTypeIdentifierDietaryCarbohydrates" sourceName="Nutrino" sourceVersion="2.15.0.6" unit="g" creationDate="2017-11-02 11:22:21 +0200" startDate="2017-11-03 00:00:00 +0200" endDate="2017-11-03 00:00:00 +0200" value="6.23">
   <MetadataEntry key="Meal" value="meal"/>
   <MetadataEntry key="HKFoodType" value="Air-Popped Popcorn"/>
  </Record>
  <Record type="HKQuantityTypeIdentifierDietaryFatTotal" sourceName="Nutrino" sourceVersion="2.15.0.6" unit="g" creationDate="2017-11-02 11:22:21 +0200" startDate="2017-11-03 00:00:00 +0200" endDate="2017-11-03 00:00:00 +0200" value="0.34">
   <MetadataEntry key="Meal" value="meal"/>
   <MetadataEntry key="HKFoodType" value="Air-Popped Popcorn"/>
  </Record>
  <Record type="HKQuantityTypeIdentifierDietaryEnergyConsumed" sourceName="Nutrino" sourceVersion="2.15.0.6" unit="kcal" creationDate="2017-11-02 11:22:21 +0200" startDate="2017-11-03 00:00:00 +0200" endDate="2017-11-03 00:00:00 +0200" value="30.6">
   <MetadataEntry key="Meal" value="meal"/>
   <MetadataEntry key="HKFoodType" value="Air-Popped Popcorn"/>
  </Record>
  <Record type="HKQuantityTypeIdentifierDietaryProtein" sourceName="Nutrino" sourceVersion="2.15.0.6" unit="g" creationDate="2017-11-02 11:22:21 +0200" startDate="2017-11-03 00:00:00 +0200" endDate="2017-11-03 00:00:00 +0200" value="1">
   <MetadataEntry key="Meal" value="meal"/>
   <MetadataEntry key="HKFoodType" value="Air-Popped Popcorn"/>
  </Record>
 </Correlation>
 <Correlation type="HKCorrelationTypeIdentifierFood" sourceName="Nutrino" sourceVersion="2.15.0.6" creationDate="2017-11-02 11:22:21 +0200" startDate="2017-11-03 00:00:00 +0200" endDate="2017-11-03 00:00:00 +0200">
  <MetadataEntry key="HKExternalUUID" value="acu0jkcg#AV98CcuAPgcAXyyTJ4Xq"/>
  <MetadataEntry key="HKFoodType" value="Red Snapper &amp; Pineapple Salsa"/>
  <Record type="HKQuantityTypeIdentifierDietaryProtein" sourceName="Nutrino" sourceVersion="2.15.0.6" unit="g" creationDate="2017-11-02 11:22:21 +0200" startDate="2017-11-03 00:00:00 +0200" endDate="2017-11-03 00:00:00 +0200" value="4">
   <MetadataEntry key="Meal" value="meal"/>
   <MetadataEntry key="HKFoodType" value="Red Snapper &amp; Pineapple Salsa"/>
  </Record>
  <Record type="HKQuantityTypeIdentifierDietaryCarbohydrates" sourceName="Nutrino" sourceVersion="2.15.0.6" unit="g" creationDate="2017-11-02 11:22:21 +0200" startDate="2017-11-03 00:00:00 +0200" endDate="2017-11-03 00:00:00 +0200" value="28">
   <MetadataEntry key="Meal" value="meal"/>
   <MetadataEntry key="HKFoodType" value="Red Snapper &amp; Pineapple Salsa"/>
  </Record>
  <Record type="HKQuantityTypeIdentifierDietaryFatTotal" sourceName="Nutrino" sourceVersion="2.15.0.6" unit="g" creationDate="2017-11-02 11:22:21 +0200" startDate="2017-11-03 00:00:00 +0200" endDate="2017-11-03 00:00:00 +0200" value="7">
   <MetadataEntry key="Meal" value="meal"/>
   <MetadataEntry key="HKFoodType" value="Red Snapper &amp; Pineapple Salsa"/>
  </Record>
  <Record type="HKQuantityTypeIdentifierDietaryEnergyConsumed" sourceName="Nutrino" sourceVersion="2.15.0.6" unit="kcal" creationDate="2017-11-02 11:22:21 +0200" startDate="2017-11-03 00:00:00 +0200" endDate="2017-11-03 00:00:00 +0200" value="160">
   <MetadataEntry key="Meal" value="meal"/>
   <MetadataEntry key="HKFoodType" value="Red Snapper &amp; Pineapple Salsa"/>
  </Record>
 </Correlation>
 <Correlation type="HKCorrelationTypeIdentifierFood" sourceName="Nutrino" sourceVersion="2.15.0.6" creationDate="2017-11-02 11:22:21 +0200" startDate="2017-11-03 00:00:00 +0200" endDate="2017-11-03 00:00:00 +0200">
  <MetadataEntry key="HKExternalUUID" value="acu0jkcg#AV98CcuAPgcAXyyTJ4Xr"/>
  <MetadataEntry key="HKFoodType" value="Rosemary Crackers"/>
  <Record type="HKQuantityTypeIdentifierDietaryCarbohydrates" sourceName="Nutrino" sourceVersion="2.15.0.6" unit="g" creationDate="2017-11-02 11:22:21 +0200" startDate="2017-11-03 00:00:00 +0200" endDate="2017-11-03 00:00:00 +0200" value="0">
   <MetadataEntry key="Meal" value="meal"/>
   <MetadataEntry key="HKFoodType" value="Rosemary Crackers"/>
  </Record>
  <Record type="HKQuantityTypeIdentifierDietaryEnergyConsumed" sourceName="Nutrino" sourceVersion="2.15.0.6" unit="kcal" creationDate="2017-11-02 11:22:21 +0200" startDate="2017-11-03 00:00:00 +0200" endDate="2017-11-03 00:00:00 +0200" value="15">
   <MetadataEntry key="Meal" value="meal"/>
   <MetadataEntry key="HKFoodType" value="Rosemary Crackers"/>
  </Record>
  <Record type="HKQuantityTypeIdentifierDietaryProtein" sourceName="Nutrino" sourceVersion="2.15.0.6" unit="g" creationDate="2017-11-02 11:22:21 +0200" startDate="2017-11-03 00:00:00 +0200" endDate="2017-11-03 00:00:00 +0200" value="1">
   <MetadataEntry key="Meal" value="meal"/>
   <MetadataEntry key="HKFoodType" value="Rosemary Crackers"/>
  </Record>
  <Record type="HKQuantityTypeIdentifierDietaryFatTotal" sourceName="Nutrino" sourceVersion="2.15.0.6" unit="g" creationDate="2017-11-02 11:22:21 +0200" startDate="2017-11-03 00:00:00 +0200" endDate="2017-11-03 00:00:00 +0200" value="1.5">
   <MetadataEntry key="Meal" value="meal"/>
   <MetadataEntry key="HKFoodType" value="Rosemary Crackers"/>
  </Record>
 </Correlation>
 <Correlation type="HKCorrelationTypeIdentifierFood" sourceName="Nutrino" sourceVersion="2.15.0.6" creationDate="2017-11-02 11:24:14 +0200" startDate="2017-11-04 00:00:00 +0200" endDate="2017-11-04 00:00:00 +0200">
  <MetadataEntry key="HKExternalUUID" value="acu0jkcg#AV98C457PgcAXyyTJ4ZG"/>
  <MetadataEntry key="HKFoodType" value="Marinated Anchovy Sandwiches"/>
  <Record type="HKQuantityTypeIdentifierDietaryFatTotal" sourceName="Nutrino" sourceVersion="2.15.0.6" unit="g" creationDate="2017-11-02 11:24:14 +0200" startDate="2017-11-04 00:00:00 +0200" endDate="2017-11-04 00:00:00 +0200" value="45">
   <MetadataEntry key="Meal" value="meal"/>
   <MetadataEntry key="HKFoodType" value="Marinated Anchovy Sandwiches"/>
  </Record>
  <Record type="HKQuantityTypeIdentifierDietaryCarbohydrates" sourceName="Nutrino" sourceVersion="2.15.0.6" unit="g" creationDate="2017-11-02 11:24:14 +0200" startDate="2017-11-04 00:00:00 +0200" endDate="2017-11-04 00:00:00 +0200" value="57">
   <MetadataEntry key="Meal" value="meal"/>
   <MetadataEntry key="HKFoodType" value="Marinated Anchovy Sandwiches"/>
  </Record>
  <Record type="HKQuantityTypeIdentifierDietaryEnergyConsumed" sourceName="Nutrino" sourceVersion="2.15.0.6" unit="kcal" creationDate="2017-11-02 11:24:14 +0200" startDate="2017-11-04 00:00:00 +0200" endDate="2017-11-04 00:00:00 +0200" value="750">
   <MetadataEntry key="Meal" value="meal"/>
   <MetadataEntry key="HKFoodType" value="Marinated Anchovy Sandwiches"/>
  </Record>
  <Record type="HKQuantityTypeIdentifierDietaryProtein" sourceName="Nutrino" sourceVersion="2.15.0.6" unit="g" creationDate="2017-11-02 11:24:14 +0200" startDate="2017-11-04 00:00:00 +0200" endDate="2017-11-04 00:00:00 +0200" value="27">
   <MetadataEntry key="Meal" value="meal"/>
   <MetadataEntry key="HKFoodType" value="Marinated Anchovy Sandwiches"/>
  </Record>
 </Correlation>
 <Correlation type="HKCorrelationTypeIdentifierFood" sourceName="Nutrino" sourceVersion="2.15.0.6" creationDate="2017-11-02 11:24:15 +0200" startDate="2017-11-04 00:00:00 +0200" endDate="2017-11-04 00:00:00 +0200">
  <MetadataEntry key="HKExternalUUID" value="acu0jkcg#AV98C457PgcAXyyTJ4ZH"/>
  <MetadataEntry key="HKFoodType" value="Salmon With Cherry Tomatoes"/>
  <Record type="HKQuantityTypeIdentifierDietaryEnergyConsumed" sourceName="Nutrino" sourceVersion="2.15.0.6" unit="kcal" creationDate="2017-11-02 11:24:15 +0200" startDate="2017-11-04 00:00:00 +0200" endDate="2017-11-04 00:00:00 +0200" value="1080">
   <MetadataEntry key="Meal" value="meal"/>
   <MetadataEntry key="HKFoodType" value="Salmon With Cherry Tomatoes"/>
  </Record>
  <Record type="HKQuantityTypeIdentifierDietaryProtein" sourceName="Nutrino" sourceVersion="2.15.0.6" unit="g" creationDate="2017-11-02 11:24:15 +0200" startDate="2017-11-04 00:00:00 +0200" endDate="2017-11-04 00:00:00 +0200" value="78">
   <MetadataEntry key="Meal" value="meal"/>
   <MetadataEntry key="HKFoodType" value="Salmon With Cherry Tomatoes"/>
  </Record>
  <Record type="HKQuantityTypeIdentifierDietaryFatTotal" sourceName="Nutrino" sourceVersion="2.15.0.6" unit="g" creationDate="2017-11-02 11:24:15 +0200" startDate="2017-11-04 00:00:00 +0200" endDate="2017-11-04 00:00:00 +0200" value="64">
   <MetadataEntry key="Meal" value="meal"/>
   <MetadataEntry key="HKFoodType" value="Salmon With Cherry Tomatoes"/>
  </Record>
  <Record type="HKQuantityTypeIdentifierDietaryCarbohydrates" sourceName="Nutrino" sourceVersion="2.15.0.6" unit="g" creationDate="2017-11-02 11:24:15 +0200" startDate="2017-11-04 00:00:00 +0200" endDate="2017-11-04 00:00:00 +0200" value="42">
   <MetadataEntry key="Meal" value="meal"/>
   <MetadataEntry key="HKFoodType" value="Salmon With Cherry Tomatoes"/>
  </Record>
 </Correlation>
 <Correlation type="HKCorrelationTypeIdentifierFood" sourceName="Nutrino" sourceVersion="2.15.0.6" creationDate="2017-11-05 10:22:03 +0200" startDate="2017-11-05 00:00:00 +0200" endDate="2017-11-05 00:00:00 +0200">
  <MetadataEntry key="HKExternalUUID" value="acu0jkcg#AV-LRbZrPgcAXyyTNu-s"/>
  <MetadataEntry key="HKFoodType" value="Bananas"/>
  <Record type="HKQuantityTypeIdentifierDietaryProtein" sourceName="Nutrino" sourceVersion="2.15.0.6" unit="g" creationDate="2017-11-05 10:22:03 +0200" startDate="2017-11-05 00:00:00 +0200" endDate="2017-11-05 00:00:00 +0200" value="1.2862">
   <MetadataEntry key="Meal" value="meal"/>
   <MetadataEntry key="HKFoodType" value="Bananas"/>
  </Record>
  <Record type="HKQuantityTypeIdentifierDietaryEnergyConsumed" sourceName="Nutrino" sourceVersion="2.15.0.6" unit="kcal" creationDate="2017-11-05 10:22:03 +0200" startDate="2017-11-05 00:00:00 +0200" endDate="2017-11-05 00:00:00 +0200" value="104.631">
   <MetadataEntry key="Meal" value="meal"/>
   <MetadataEntry key="HKFoodType" value="Bananas"/>
  </Record>
  <Record type="HKQuantityTypeIdentifierDietaryCarbohydrates" sourceName="Nutrino" sourceVersion="2.15.0.6" unit="g" creationDate="2017-11-05 10:22:03 +0200" startDate="2017-11-05 00:00:00 +0200" endDate="2017-11-05 00:00:00 +0200" value="26.9512">
   <MetadataEntry key="Meal" value="meal"/>
   <MetadataEntry key="HKFoodType" value="Bananas"/>
  </Record>
  <Record type="HKQuantityTypeIdentifierDietaryFatTotal" sourceName="Nutrino" sourceVersion="2.15.0.6" unit="g" creationDate="2017-11-05 10:22:03 +0200" startDate="2017-11-05 00:00:00 +0200" endDate="2017-11-05 00:00:00 +0200" value="0.3894">
   <MetadataEntry key="Meal" value="meal"/>
   <MetadataEntry key="HKFoodType" value="Bananas"/>
  </Record>
 </Correlation>
 <Correlation type="HKCorrelationTypeIdentifierFood" sourceName="Nutrino" sourceVersion="2.15.0.6" creationDate="2017-11-05 10:28:00 +0200" startDate="2017-11-05 00:00:00 +0200" endDate="2017-11-05 00:00:00 +0200">
  <MetadataEntry key="HKExternalUUID" value="acu0jkcg#AV-LSysi8akmkjRi6_IH"/>
  <MetadataEntry key="HKFoodType" value="Bananas"/>
  <Record type="HKQuantityTypeIdentifierDietaryCarbohydrates" sourceName="Nutrino" sourceVersion="2.15.0.6" unit="g" creationDate="2017-11-05 10:28:00 +0200" startDate="2017-11-05 00:00:00 +0200" endDate="2017-11-05 00:00:00 +0200" value="26.9512">
   <MetadataEntry key="Meal" value="meal"/>
   <MetadataEntry key="HKFoodType" value="Bananas"/>
  </Record>
  <Record type="HKQuantityTypeIdentifierDietaryProtein" sourceName="Nutrino" sourceVersion="2.15.0.6" unit="g" creationDate="2017-11-05 10:28:00 +0200" startDate="2017-11-05 00:00:00 +0200" endDate="2017-11-05 00:00:00 +0200" value="1.2862">
   <MetadataEntry key="Meal" value="meal"/>
   <MetadataEntry key="HKFoodType" value="Bananas"/>
  </Record>
  <Record type="HKQuantityTypeIdentifierDietaryEnergyConsumed" sourceName="Nutrino" sourceVersion="2.15.0.6" unit="kcal" creationDate="2017-11-05 10:28:00 +0200" startDate="2017-11-05 00:00:00 +0200" endDate="2017-11-05 00:00:00 +0200" value="104.631">
   <MetadataEntry key="Meal" value="meal"/>
   <MetadataEntry key="HKFoodType" value="Bananas"/>
  </Record>
  <Record type="HKQuantityTypeIdentifierDietaryFatTotal" sourceName="Nutrino" sourceVersion="2.15.0.6" unit="g" creationDate="2017-11-05 10:28:00 +0200" startDate="2017-11-05 00:00:00 +0200" endDate="2017-11-05 00:00:00 +0200" value="0.3894">
   <MetadataEntry key="Meal" value="meal"/>
   <MetadataEntry key="HKFoodType" value="Bananas"/>
  </Record>
 </Correlation>
 <Correlation type="HKCorrelationTypeIdentifierFood" sourceName="Nutrino" sourceVersion="2.15.0.6" creationDate="2017-11-05 10:28:14 +0200" startDate="2017-11-05 00:00:00 +0200" endDate="2017-11-05 00:00:00 +0200">
  <MetadataEntry key="HKExternalUUID" value="acu0jkcg#AV-LS2J2PgcAXyyTNvCi"/>
  <MetadataEntry key="HKFoodType" value="Cucumber"/>
  <Record type="HKQuantityTypeIdentifierDietaryCarbohydrates" sourceName="Nutrino" sourceVersion="2.15.0.6" unit="g" creationDate="2017-11-05 10:28:14 +0200" startDate="2017-11-05 00:00:00 +0200" endDate="2017-11-05 00:00:00 +0200" value="7.2963">
   <MetadataEntry key="Meal" value="meal"/>
   <MetadataEntry key="HKFoodType" value="Cucumber"/>
  </Record>
  <Record type="HKQuantityTypeIdentifierDietaryEnergyConsumed" sourceName="Nutrino" sourceVersion="2.15.0.6" unit="kcal" creationDate="2017-11-05 10:28:14 +0200" startDate="2017-11-05 00:00:00 +0200" endDate="2017-11-05 00:00:00 +0200" value="31.2354">
   <MetadataEntry key="Meal" value="meal"/>
   <MetadataEntry key="HKFoodType" value="Cucumber"/>
  </Record>
  <Record type="HKQuantityTypeIdentifierDietaryProtein" sourceName="Nutrino" sourceVersion="2.15.0.6" unit="g" creationDate="2017-11-05 10:28:14 +0200" startDate="2017-11-05 00:00:00 +0200" endDate="2017-11-05 00:00:00 +0200" value="1.3065">
   <MetadataEntry key="Meal" value="meal"/>
   <MetadataEntry key="HKFoodType" value="Cucumber"/>
  </Record>
  <Record type="HKQuantityTypeIdentifierDietaryFatTotal" sourceName="Nutrino" sourceVersion="2.15.0.6" unit="g" creationDate="2017-11-05 10:28:14 +0200" startDate="2017-11-05 00:00:00 +0200" endDate="2017-11-05 00:00:00 +0200" value="0.2211">
   <MetadataEntry key="Meal" value="meal"/>
   <MetadataEntry key="HKFoodType" value="Cucumber"/>
  </Record>
 </Correlation>